<?php
/**
 * Listado Comunas de Chile por Regiones
 * @link       https://marketingrapel.cl
 * @since      1.0.0
 * @package    wc-ciudades-y-regiones-de-chile
 * @subpackage wc-ciudades-y-regiones-de-chile/places
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
 
global $places;

$places['CL'] = array(
	'PY-ASU' => array(
        'Asunción',
        'Luque',
        'San Lorenzo',
        'Capiatá',
        'Lambaré',
        'Fernando de la Mora',
        'Limpio',
        'Ñemby',
        'Itauguá',
        'Mariano Roque Alonso',
        'Itá',
        'Villa Elisa',
        'Areguá',
        'San Antonio',
        'Ypané',
        'Saldívar',
        'Villeta',
        'Guarambaré',
        'Ypacaraí',
        'Nueva Italia'
	),
	'PY-1' => array(
        'Belén',
        'Concepción',
        'Horqueta',
        'Loreto',
        'Paso Barreto',
        'Paso Mbutú',
        'Puerto Fonciere',
        'San Carlos',
        'San Lázaro',
        'Valle-Mí',
        'Yby - Yau'
     ),   
	'PY-2' => array(
		'Antequera',
		'Capiibary',
		'Choré',
		'General Elizardo Aquino',
		'General Isidoro Resquín',
		'Guayaibí',
		'Itacurubí del Rosario',
		'Liberación',
		'Lima',
		'Nueva Germania',
		'San Estanislao',
		'San Pablo',
		'San Pedro del Ycuamandyyú',
		'Santa Rosa del Aguaray',
		'San Vicente Pancholo',
		'Tacuatí',
		'Unión',
		'25 de Diciembre',
		'Villa del Rosario',
		'Yataity del Norte',
		'Yrybucuá',
		'San José del Rosario'
	),
	'PY-3' => array(
		'Altos',
		'Arroyos y Esteros',
		'Atyrá',
		'Caacupé',
		'Caraguatay',
		'Emboscada',
		'Eusebio Ayala',
		'Isla Pucú',
		'Itacurubí de la Cordillera',
		'Juan de Mena',
		'Loma Grande',
		'Mbocayaty del Yhaguy',
		'Nueva Colombia',
		'Piribebuy',
		'Primero de Marzo',
		'San Bernardino',
		'San José Obrero',
		'Santa Elena',
		'Tobatí',
		'Valenzuela'
	),
	'PY-4' => array(
		'Borja',
		'Capitán Mauricio José Troche',
		'Coronel Martínez',
		'Doctor Bottrell',
		'Félix Pérez Cardozo',
		'General Eugenio A. Garay',
		'Independencia',
		'Itapé',
		'Iturbe',
		'José Fassardi',
		'Mbocayaty',
		'Natalicio Talavera',
		'Ñumí',
		'Paso Yobai',
		'San Salvador',
		'Tebicuary',
		'Villarrica',
		'Yataity'
	),
	'PY-5' => array(
		'Caaguazú',
		'Carayaó',
		'Coronel Oviedo',
		'Doctor Cecilio Báez',
		'Doctor Juan Eulogio Estigarribia',
		'Doctor Juan Manuel Frutos',
		'José Domingo Ocampos',
		'La Pastora',
		'Mariscal Francisco Solano López',
		'Nueva Londres',
		'Nueva Toledo',
		'Raúl Arsenio Oviedo',
		'Regimiento de Infantería Tres Corrales',
		'Repatriación',
		'San José de los Arroyos',
		'San Joaquín',
		'Santa Rosa del Mbutuy',
		'Simón Bolívar',
		'Tembiaporá',
		'Tres de Febrero',
		'Vaquería',
		'Yhú'
	),
	'PY-6' => array(
		'Abaí',
		'Buena Vista',
		'Caazapá',
		'Doctor Moisés S. Bertoni',
		'Fulgencio Yegros',
		'General Higinio Morínigo',
		'Maciel',
		'San Juan Nepomuceno',
		'Tavaí',
		'Tres de Mayo',
		'Yuty'
	),
	'PY-7' => array(
		'Alto Verá',
		'Bella Vista',
		'Cambyretá',
		'Capitán Meza',
		'Capitán Miranda',
		'Carlos Antonio López',
		'Carmen del Paraná',
		'Coronel José Félix Bogado',
		'Edelira',
		'Encarnación',
		'Fram',
		'General Artigas',
		'General Delgado',
		'Hohenau',
		'Itapúa Poty',
		'José Leandro Oviedo',
		'La Paz',
		'Mayor Julio Dionisio Otaño',
		'Natalio',
		'Nueva Alborada',
		'Obligado',
		'Pirapó',
		'San Cosme y Damián',
		'San Juan del Paraná',
		'San Pedro del Paraná',
		'San Rafael del Paraná',
		'Tomás Romero Pereira',
		'Trinidad',
		'Yatytay'
	),
	'PY-8' => array(
		'Ayolas',
		'San Ignacio',
		'San Juan Bautista',
		'San Miguel',
		'San Patricio',
		'Santa María',
		'Santa Rosa',
		'Santiago',
		'Villa Florida',
		'Yabebyry'
	),
	'PY-9' => array(
		'Acahay',
		'Caapucú',
		'Carapeguá',
		'Escobar',
		'General Bernardino Caballero',
		'La Colmena',
		'María Antonia',
		'Mbuyapey',
		'Paraguarí',
		'Pirayú',
		'Quiindy',
		'Quyquyhó',
		'San Roque González de Santa Cruz',
		'Sapucai',
		'Tebicuarymí',
		'Yaguarón',
		'Ybycuí',
		'Ybytymí'
	),
	'PY-10' => array(
		'Ciudad del Este',
		'Doctor Juan León Mallorquín',
		'Doctor Raúl Peña',
		'Domingo Martínez de Irala',
		'Hernandarias',
		'Iruña',
		'Itakyry',
		'Juan Emilio O\' Leary',
		'Los Cedrales',
		'Mbaracayú',
		'Minga Guazú',
		'Minga Porá',
		'Naranjal',
		'Ñacunday',
		'Presidente Franco',
		'San Alberto',
		'San Cristóbal',
		'Santa Fe del Paraná',
		'Santa Rita',
		'Santa Rosa del Monday',
		'Tavapy',
		'Yguazú'
	),
	'PY-12' => array(
		'Alberdi',
		'Cerrito',
		'Desmochados',
		'General José Eduvigis Díaz',
		'Guazú Cuá',
		'Humaitá',
		'Isla Umbú',
		'Laureles',
		'Mayor José de Jesús Martínez',
		'Paso de Patria',
		'Pilar',
		'San Juan Bautista del Ñeembucú',
		'Tacuaras',
		'Villa Franca',
		'Villa Oliva',
		'Villalbín'

	),
	'PY-13' => array(
		'Bella Vista',
		'Capitán Bado',
		'Cerro Corá',
		'Karapaí',
		'Pedro Juan Caballero',
		'Zanja Pytá'
	),
	'PY-14' => array(
		'Corpus Christi',
		'Curuguaty',
		'General Francisco Caballero Álvarez',
		'Itanará',
		'Katueté',
		'La Paloma del Espíritu Santo',
		'Laurel',
		'Maracaná',
		'Nueva Esperanza',
		'Puerto Adela',
		'Salto del Guairá',
		'Villa Ygatimí',
		'Yasy Cañy',
		'Yby Pytá',
		'Ybyrarobaná',
		'Ypejhú'
	),
	'PY-15' => array(
		'Benjamín Aceval',
		'Campo Aceval',
		'José Falcón',
		'General José María Bruguez',
		'Nanawa',
		'Nueva Asunción',
		'Puerto Pinasco',
		'Teniente Primero Manuel Irala Fernández',
		'Teniente Esteban Martínez',
		'Villa Hayes'
	),
	'PY-16' => array(
		'Neuland',
		'Filadelfia',
		'Loma Plata',
		'Mariscal José Félix Estigarribia'
	),
	'PY-17' => array(
		'Bahía Negra',
		'Capitán Carmelo Peralta',
		'Fuerte Olimpo',
		'Puerto Casado'
	)

);